name: Pruebas de Python

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requerimientos.txt

      - name: Ejecutar pruebas con pytest
        run: pytest